[appenders.display]
kind = "async_console"
pattern = "{l} {d(%H:%M:%S.%f)} [{M} #FS#{f}#FE#:{L}] {m}{n}"

[[appenders.display.filters]]
kind  = "threshold"
level = "info"

[appenders.async_file]
kind = "async_file"
output_file_name = "client.log"
pattern = "{l} {d(%H:%M:%S.%f)} [{M} #FS#{f}#FE#:{L}] {m}{n}"
append = true
file_timestamp = true

[loggers."client"]
level = "trace"
appenders = ["display", "async_file"]

[loggers."crust"]
level = "warn"
appenders = ["display", "async_file"]

[loggers."p2p"]
level = "trace"
appenders = ["display", "async_file"]

